### ISSUE TITLE
User certificate SCEPman URL: `http://` or `https://`?

### ISSUE THREAD

**Issue by o-l-a-v** [scepman/scepman-docs#6]
Following doc for user certificates is ambiguous when it comes to protocol in "SCEP Server URLs".

* <https://docs.scepman.com/certificate-deployment/microsoft-intune/windows-10#user-certificates>

The text says to follow device certificate procedure, except for three specific things. That would include to copy "SCEP Server URL" straight from the SCEPman instance, which includes `https://`.

But the screenshot example from this doc clearly shows `http://`.

<img width="574" alt="image" src="https://github.com/scepman/scepman-docs/assets/6450056/d6a62d05-725f-40d9-84c2-f43bdf433c57">

Which is it?

**Comment by Eyad404** [comment]
Hi @o-l-a-v, 
`https://` is the right one. We will update the screenshot of user certificate ! Thanks for the reporting!

**Comment by Eyad404** [comment]
screenshot already updated
